### ISSUE TITLE
Tree does not reflect the changes when data is updating

### ISSUE THREAD

**Issue by Marius-AdamDT** [brimdata/react-arborist#109]
I'm passing data to `initialData` prop. The data is coming from BE and is dynamic based on some external filtering.
I can correctly see the data updating, however the tree does not reflect the changes. 

I've also tried the `useSimpleTree` hook and passed the `mutableData` to the data prop however I'm experiencing the same behaviour.

How can we make the tree dynamic based on the passed data?

**Comment by jameskerr** [comment]
Pass your data to the `data` prop instead of the `initialData` prop.

**Comment by Marius-AdamDT** [comment]
@jameskerr yep, that's what I ended up doing, however we must handle all the data modifications ourselves in this case.

**Comment by Gab1988** [comment]
I would also report that I'm getting errors since keys get duplicated after deleting a node.
I'm using react/react-dom 18.2.0 and react-arborist 3.0.2 and like @Marius-AdamDT I'm using the data prop only since the changes I need to apply are managed outside the Tree component

**Comment by Gab1988** [comment]
Sorry my bad on this one, I was for whatever reason re-rendering while I had duplicated keys in my tree

**Comment by jameskerr** [comment]
I've made that same mistake myself. Glad you found the fix.
