### ISSUE TITLE
Feature request: option to not filter out children of matched nodes

### ISSUE THREAD

**Issue by cers** [brimdata/react-arborist#111]
Take your `cities` example: if you search for `Alabama` then you cannot see the cities inside of it.

Confusingly, you can still toggle it open and closed, even though it has no visible children. It would be great if the children were still accessible, but not open by default. Maybe even with a an exposed property to let you know if a node is a matching element or not.

**Comment by jameskerr** [comment]
You're right. That is confusing behavior.

**Comment by zachristmas** [comment]
Following this one. Out of all of the feature requests, this one would provide the most value IMO. I'm open to helping implement this, would just need some pointers on where to start :)

**Comment by jameskerr** [comment]
I just remembered that we already expose a Tree prop to customize the matching behavior for the filtering.

```ts
searchMatch?: (node: NodeApi<T>, searchTerm: string) => boolean;
```

You can create your own custom matching function for the tree to use when it filters.

**Comment by zachristmas** [comment]
I'll tinker around with it, returning the children for a matching parent shouldn't be too crazy. Thanks for the clarification.

**Comment by jameskerr** [comment]
I'm closing this since it seems with enough thinking, this can be done with the current API. If anyone finds a more intuitive default however, please let me know.
