### ISSUE TITLE
Feature request: prop to pass context to DndProvider

### ISSUE THREAD

**Issue by cers** [brimdata/react-arborist#114]
We need to pass `context={window}` to the `DndProvider` that lives in provider.tsx - otherwise we get the error:

> Cannot have two HTML5 backends at the same time.

Would it be possible to add an optional prop to TreeApi like `dndContext` and pass that along?

I can provide a PR if that helps

**Comment by jameskerr** [comment]
I think others have been able to get around this by passing a different element to the existing tree prop: `dndRootElement?: globalThis.Node | null`;

**Comment by jameskerr** [comment]
See https://github.com/brimdata/react-arborist/issues/17 and https://github.com/brimdata/react-arborist/pull/33 if they are any help.

**Comment by FindDefinition** [comment]
@jameskerr we need external dnd context to drag react-arborist tree item to external drop target. currently there is no way to implement this feature in a clean way, I have to use a additional useDrag hook and get a weird result:
![output1](https://user-images.githubusercontent.com/73811981/224381983-a9bb5e4c-4991-4b30-84e0-f5f64043b7b8.gif)
If I modify react-arborist source code with external context support, everything works fine.

**Comment by jameskerr** [comment]
Let's do it. What modifications did you make? Please submit a PR.

**Comment by masoi1289** [comment]
@FindDefinition  How you can change the icon when dragging and dropping? I want my cursor ' grab' and grabing.
Can you support me? Thanks.

**Comment by jameskerr** [comment]
This was closed in the latest release. You can now provide the dndManager prop to the Tree component.
