### ISSUE TITLE
Bug with closing nodes, when they are matched with search string

### ISSUE THREAD

**Issue by SidorenkoDenis1989** [brimdata/react-arborist#115]
There is problem when tree is deeper, than 2 levels, and you try to close parent nodes after filtering the tree.

![image](https://user-images.githubusercontent.com/64959069/217873625-37d1ce24-8ae4-4091-a083-8704f38d2481.png)
![image](https://user-images.githubusercontent.com/64959069/217876078-6621981e-1287-4619-9777-b397176dfcbe.png)

When you try to close node with name "Chat Rooms" it will close only next level children ("Open Source Projects"), but not all its children. As I can understand node "test" also must be closed.

It is a problem when you have a lot of data. I tried to change seacrhMath function, and close all clindren of node "Chat Rooms" after calling .close() method, but it's realy bad idea)

**Comment by jameskerr** [comment]
Thank you for reporting. That is indeed a bug. Here's the Fix: https://github.com/brimdata/react-arborist/pull/116
