### ISSUE TITLE
Is it possible to select a node without focusing it

### ISSUE THREAD

**Issue by wrobbinz** [brimdata/react-arborist#117]
If using the `selection` prop, when the selection changes, the tree focuses that node. I believe that the "stealing" of focus has negative a11y implications because, in a scenario where an external action changes the `selection`, the focus snaps to the tree, disorienting a keyboard user.

For example, if the `selection` prop is bound to the URL, then as a user clicks links across the application, the tree will correctly select and scroll to the appropriate node, but it will steal focus away from where the user last took action.

I _think_ that if possible, the useEffect that changes selection (in provider.tsx) should select without focusing. Is that possible to do? Does anything like scrollToItem rely on a node being focused that would make NOT focusing a node on selection a problem?

**Comment by jameskerr** [comment]
You make a great point. The selection shouldn't be stolen from other things when that prop changes.

**Comment by jameskerr** [comment]
I'll put up a PR shortly.

**Comment by wrobbinz** [comment]
Wow, awesome. Thank you! Particularly noticed this because the programatic nature of the focus() call triggers the `:focus-visible` styles on the node. So this is a win for a11y and aesthetics.
