### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by plgagnon2** [brimdata/react-arborist#12]
Is this planned?

**Comment by jameskerr** [comment]
I am using this library for a desktop electron app, so mobile is not my first use case. However, it is just web tech so it's probably bearable on mobile. And I'm open to contributions to improve the mobile experience. What's your use case you'd hope this helps with?

**Comment by plgagnon2** [comment]
Well the drag n drop feature doesnt seem to work on mobile

**Comment by jameskerr** [comment]
To be transparent, I don't use this with mobile apps so I won't be the one to work on making sure it works for mobile. Hope you can find something else that suits your needs. 

I'll leave this issue open in case a generous person wants to give it a shot.
