### ISSUE TITLE
Multiple selection of nodes using checkboxes

### ISSUE THREAD

**Issue by SoniaGarciaMind** [brimdata/react-arborist#120]
I am trying to select multiple tree nodes using checkboxes but when I check one, the other selected node is deselected. The only way I could select more than one would be to use the control key and select the corresponding checkbox but this way does not fit the requirements I have been asked for. Could there be a solution that I am not aware of?
Thanks for your help!

**Comment by jameskerr** [comment]
Yeah, in your click handler for the checkbox, call `node.selectMulti()`. The will preserve other selections. And it will deselect properly I believe.

**Comment by SoniaGarciaMind** [comment]
When you click on the checkbox the other checkboxes are deselected even if selectMulti is used, only if you use the control key and click on the checkbox the previously selected checkboxes are kept.

**Comment by jameskerr** [comment]
What's your code look like?

**Comment by SoniaGarciaMind** [comment]
This is the code related to the node 
`{
        selectable &&
        !node.data.children?.length &&
        <Checkbox
          style={{ padding: 0 }}
          checked={node.state.isSelected}
          onClick={() => tree.selectMulti(node.id)} />
      }`

**Comment by sandragjacinto** [comment]
Hi  @jameskerr  I  noticed that the multi selection requires the ctrl key to be pressed, is there a way to make it available by default, avoinding this requirement ? Thanks !

**Comment by sandragjacinto** [comment]
Hi @jameskerr , thanks for this lib ! I'm having an issue associated to the selectMulti it seems that the SELECT_ONLY is always dispatched even when using selectMulti, how could i bypass this ? thanks !

**Comment by jameskerr** [comment]
Oh! Perhaps this is what's going on.

You may need to call `event.stopPropagation()` on the event argument in your NodeRenderer's onClick event. Each node is wrapped in a Row component. The Default Row component provided in the library binds the onClick event.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/3460638/221008675-f1bc6495-aef0-414e-b5ef-2584a750af1d.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/3460638/221008750-c824882a-d2fc-4832-9c6c-42cd37fc4139.png">

So either stopPropagation in your onClick handler, or provide a custom RowRenderer that doesn't have an onClick handler.

**Comment by jameskerr** [comment]
I hope this has addressed this issue. I am now closing.

**Comment by anupsingh244** [comment]
How can i deselect the node, without key shortcut, i have checkbox multiselect tree and I want to select/deselect the selection if clicked on checkbox. It is not happening right now, I am not able to deselect on checkbox click.

**Comment by jameskerr** [comment]
@anupsingh244 Are you able to share the code that is not working?
