### ISSUE TITLE
Can't drag/drop in iframe

### ISSUE THREAD

**Issue by thang-nhatrangart** [brimdata/react-arborist#121]
I am having a problem with drag-and-drop functionality in an iframe. After conducting some research, I found a solution using DnDProvider. You can find the link to the solution here: 
https://react-dnd.github.io/react-dnd/examples/dustbin/iframe. 
Could you please add the context props to the DnDProvider component? Thank you very much.

**Comment by jameskerr** [comment]
I'm not sure I understand the issue you are having, but it seems related to #114. I will close this and reference it in that issue.
