### ISSUE TITLE
Retrieve not visible selectedNodes

### ISSUE THREAD

**Issue by sandragjacinto** [brimdata/react-arborist#125]
I am trying to retrieve selected nodes in a tree that can be open or closed :

![image](https://user-images.githubusercontent.com/9394996/220909398-78ad3a8d-9ef5-40d9-8bce-42ff09727418.png)

![image](https://user-images.githubusercontent.com/9394996/220909843-6a453181-5eec-41b7-a074-aded943fd219.png)

The goal is to display the number of selected leafs independently of whether the tree is opened or closed

![image](https://user-images.githubusercontent.com/9394996/220910383-6cd402c2-c3be-4d4a-ba9c-d1f9d39861bc.png)
![image](https://user-images.githubusercontent.com/9394996/220910470-7e3dc880-3d8a-4c81-8e54-e6708d0f5ab0.png)

I couldn't find a way of getting this info using the available API because selectedNodes are filtered based on visibleNodes. If I use the selectedIds the issue I encounter is filtering out the ids that don't correspond to leafs

**Comment by jameskerr** [comment]
Hello @sandragjacinto, thank you for the screenshots. I understand your issue. As a work around for today, you'll need to use the `tree.root` property and the `tree.selectedIds` property.

First make a function that flattens the nodes in the tree based on the root node. Here's a modified version of the `flattenTree(root)` function found in src/data/create-list.ts. 

```ts
function flattenTree<T>(root: NodeApi<T>): NodeApi<T>[] {
  const list: NodeApi<T>[] = [];
  function collect(node: NodeApi<T>) {
    if (node.level >= 0) list.push(node);
    node.children?.forEach(collect);
  }
  collect(root);
  return list;
}
```

So your code would looks something like this:

```ts
function getAllSelectedNodes(tree: TreeApi<any>) {
  const list = flattenTree(tree.root);
  return list.filter(node => tree.selectedIds.has(node.id))
}
```

**Comment by sandragjacinto** [comment]
> Hello @sandragjacinto, thank you for the screenshots. I understand your issue. As a work around for today, you'll need to use the `tree.root` property and the `tree.selectedIds` property.
> 
> First make a function that flattens the nodes in the tree based on the root node. Here's a modified version of the `flattenTree(root)` function found in src/data/create-list.ts.
> 
> ```ts
> function flattenTree<T>(root: NodeApi<T>): NodeApi<T>[] {
>   const list: NodeApi<T>[] = [];
>   function collect(node: NodeApi<T>) {
>     if (node.level >= 0) list.push(node);
>     node.children?.forEach(collect);
>   }
>   collect(root);
>   return list;
> }
> ```
> 
> So your code would looks something like this:
> 
> ```ts
> function getAllSelectedNodes(tree: TreeApi<any>) {
>   const list = flattenTree(tree.root);
>   return list.filter(node => tree.selectedIds.has(node.id))
> }
> ```
thanks ! this worked well I just had to adapt the flattenTree code so the condition pushes to list when node has not children (AKA is a leaf) instead of node.level (since i don't know beforehand the number of levels my tree will have) 👌 

thanks for the reply

**Comment by sandragjacinto** [comment]
hi @jameskerr  thanks ! this worked well I just had to adapt the flattenTree code so the condition pushes to list when node has not children (AKA is a leaf) instead of node.level (since i don't know beforehand the number of levels my tree will have) 👌

thanks for the reply

**Comment by jameskerr** [comment]
Awesome, glad it worked!
