### ISSUE TITLE
Using the Tree.selection attribute with a custom Node applies blue line styles to the row of the selected node. 

### ISSUE THREAD

**Issue by mildavw** [brimdata/react-arborist#126]
If you define a custom node and want to render the tree with an initial node selected, using the Tree `selection` attribute styles the row of the selected node with blue lines on the top and bottom. 

![Screenshot 2023-02-23 at 1 28 46 PM](https://user-images.githubusercontent.com/213468/221034498-5c617185-8355-4af4-8bb1-de10c9f221b5.png)

Here's a demo where the blue lines appear on the first render and then disappear when you select other nodes by clicking.

https://codesandbox.io/s/the-simplest-tree-forked-x91wir?file=/src/App.tsx

**Comment by jameskerr** [comment]
That it the browser's default styles for an element that has focus. If you want to change the focus styles for a selected node, you can can target it with this css selector:

```css
[role=treeitem]:focus-visible {}
[role=treeitem]:focus {}
```

For the differences between focus and focus-visible, see this article: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

**Comment by mildavw** [comment]
Ahh, gotcha. Was your thinking that if a page is loaded with a large tree with a node selected, it should receive special treatment with focus-visible?

**Comment by jameskerr** [comment]
The browser chooses when to apply the "focus-visible" styles, but the heuristic is generally: if you are using the keyboard and pressing tab, style it with :focus-visible, but if you're using a mouse don't apply focus-visible, only :focus.

**Comment by mildavw** [comment]
Got it. Thanks for the explanation. And also for the good work on this component! I'm very happy with it so far. It seems to be unique in its flexibility among draggable tree widgets. Nice work!

**Comment by jameskerr** [comment]
Thank you!
