### ISSUE TITLE
Lazy loading children when parent is opened

### ISSUE THREAD

**Issue by waliurjs** [brimdata/react-arborist#127]
Hi, I have a large set of parents and children. I was wondering if there a way to load children nodes only when parent is clicked to open.

Interactions in a nutshell:
- All parents are in collapsed state at the beginning
- User clicks a parent item
- A loading animation appears under that parent
- Then the children of that parent are fetched in the "background"
- When that request resolves, the fetched children are rendered inside that parent

Is it possible to achieve these interactions using current features of this package?

**Comment by jameskerr** [comment]
Yup, it is possible. I don't have an example of it yet, but you have all the pieces in this package to do it.

**Comment by holy-dev** [comment]
@waliurjs how you did it?

**Comment by holy-dev** [comment]
Any update?
