### ISSUE TITLE
Tree Depth seems to stop after 6 levels?

### ISSUE THREAD

**Issue by JasonLunsford** [brimdata/react-arborist#128]
Hello!

I am trying to implement a tree of n-depth. I have confirmed my data is correctly shaped (each object contains a "name" and, when appropriate, a "children" array). The tree works great - until the tree depth reaches 6 levels. After 6 no other nodes are rendering, even though the data is available and the tree height is generous.

Not sure what I can share by way of code, I'm using the sample code from the documentation and simply passing in a VERY deeply nested (but, again, correctly shaped) data structure. Is there a default depth the tree is configured to stop at? Is it possible to configure the tree to accommodate any tree depth?

Thank you.

**Comment by JasonLunsford** [comment]
Update: I do not think this is a depth issue, the problem seems to be the maximum number of nodes that can be displayed. After flattening my data source I'm still running into the issue where the tree does not show all available data, and bottoms out after 15 nodes.

**Comment by JasonLunsford** [comment]
I figured it out. Apparently the "overscanCount" needs to be set to exceed the total count of the number of tree nodes. Hopefully this helps somebody in the future.

**Comment by jameskerr** [comment]
The rows in the tree are virtualized meaning only nodes that are deemed to be "visible" using the height and the scroll Y position will be rendered. The overscanCount property let's you specify how many nodes should be rendered above and below the "visible" ones. They're waiting in the wings to afford a smoother scrolling experience.

Make sure you set the height of your tree to be the same as the containing element. I often have to use a `use-resize-observer` to get the proper height.

Good luck @JasonLunsford !
