### ISSUE TITLE
Checkbox and search support

### ISSUE THREAD

**Issue by mooijtech** [brimdata/react-arborist#13]
Hello,

I would like to replace [react-dropdown-tree-select](https://github.com/dowjones/react-dropdown-tree-select) with this library.
Would it be possible to add functionality where you can checkbox folders and search for folders?

**Comment by jameskerr** [comment]
Hi @mooijtech thanks for the question. I think you can accomplish what you want by using the [tree.selectById(id, true)](https://github.com/brimdata/react-arborist/blob/main/packages/react-arborist/src/tree-api.ts#L73) method, and the [state.isSelected](https://github.com/brimdata/react-arborist#handlers-prop) parts of the NodeRenderer's state.

The tree instance is passed to the node renderer so you can use like so.

```jsx
function NodeRenderer({data, state, tree}) {
  return ( 
     ... 
     <input type="checkbox" checked={state.isSelected} onClick={() => tree.selectById(data.id, true)} />
    ...
}

```

When I have more time, I'll put up an example of checkboxes on the demo site.

**Comment by mooijtech** [comment]
Hi James,

Finally got around to implementing this.
Using the Tree API works but doesn't allow shift-clicking to select everything between the first and last selected node (even when setting `shift` to true).

React wants to use the `onChange` event for checkboxes otherwise will show this console warning:
Warning: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.

I ended up fixing the shift-clicking by calling the `handlers` passed to the node renderer:
```js
<input
  id="row"
  name="row"
  type="checkbox"
  checked={state.isSelected}
  onClick={handlers.select}
  onChange={() => {}}
/>
```

I also needed to listen for the selection change, for which I've set the ref of the Tree component to a callback:
```js
    const onTreeChange = useCallback(tree => {
        if (tree !== null && tree.getSelectedIds().length > 0) {
            alert("Got: " + tree.getSelectedIds())
        }
    }, []);
```
A `onSelect` Tree component event would be more friendly.

**Comment by jameskerr** [comment]
I think defaultChecked will work for you case. And this seems like an okay workaround. I'm working on a version 2 that will clean this up.

**Comment by mooijtech** [comment]
Using `defaultChecked` will break keyboard up/down.
My `onChange` wasn't getting fired for keyboard events.
I just figured it out via https://github.com/facebook/react/issues/13477

The following works:
```js
<input
       id="row"
       name="row"
       type="checkbox"
       checked={state.isSelected || false} // The "|| false" is important per: https://github.com/facebook/react/issues/13477#issuecomment-659651492
       onClick={handlers.select}
       onChange={() => {
           // Debounce as this will get called for every individual tree node change (when shift-clicking)
           clearTimeout(treeNodeSelectDebounce)

           treeNodeSelectDebounce = setTimeout(() => {
                    // API call here
           }, 1000)
        }}
       />
```

**Comment by mooijtech** [comment]
I think I've found the root cause of the `onChange` not firing: https://github.com/facebook/react/issues/13424

**Comment by mooijtech** [comment]
Closed as this is solved by react-arborist v2: https://github.com/brimdata/react-arborist/pull/49#issuecomment-1286083041

**Comment by ns-kutsav** [comment]
@mooijtech can you please share the code for the demo you added for using checkboxes?
