### ISSUE TITLE
Can't `selectMulti` nonvisible nodes

### ISSUE THREAD

**Issue by victorvianaom** [brimdata/react-arborist#130]
Hello There. Using the tree api I can `.select` and `.deselect` a nonvisible node, but I'm not able to `.selectMulti` a node that is not in the view.
Inspecting the tree-api code, I found out that `.selectMulti` uses `this.get()` method, which cannot access nonvisible nodes.
I modified the `.selectMulti` method to retrieve the node id with `identify(identity);`, similar to what `.select` and `.deselect` do, and it worked, this way I can multi select nonvisible nodes.

```js
  select(node: Identity, opts: { align?: Align } = {}) {
    if (!node) return;
    const id = identify(node);
    this.dispatch(focus(id));
    this.dispatch(selection.only(id));
    this.dispatch(selection.anchor(id));
    this.dispatch(selection.mostRecent(id));
    this.scrollTo(id, opts.align);
    if (this.focusedNode) safeRun(this.props.onFocus, this.focusedNode);
    safeRun(this.props.onSelect, this.selectedNodes);
  }

  deselect(node: Identity) {
    if (!node) return;
    const id = identify(node);
    this.dispatch(selection.remove(id));
  }

  selectMulti(identity: Identity) {
    // const node = this.get(identifyNull(identity));
    if (!identity) return;
    const id = identify(identity); // new line
    this.dispatch(focus(id)); // previous node.id
    this.dispatch(selection.add(id)); // previous node.id
    this.dispatch(selection.anchor(id)); // previous node.id
    this.dispatch(selection.mostRecent(id)); // previous node.id
    this.scrollTo(identity);
    if (this.focusedNode) safeRun(this.props.onFocus, this.focusedNode);
    safeRun(this.props.onSelect, this.selectedNodes);
  }
```

My question is. What's the reason for using `this.get()` instead of directly calling `identify()` for getting the id?
And, is there any workaround for selecting multiple nonvisible nodes, other than modifying the lib?

**Comment by jameskerr** [comment]
Nope, this should be possible. It looks like there is a PR up that will fix this. I'll review that now.

**Comment by rkistinger** [comment]
@jameskerr any update on the fix here? My use case requires initializing the tree with multiple nodes selected so I am in need of this feature as well.

**Comment by jameskerr** [comment]
I'll get this fix in this week.
