### ISSUE TITLE
Library does not all to render beyond ~400000 nodes

### ISSUE THREAD

**Issue by AkankshaPushkarna** [brimdata/react-arborist#132]
While rendering the tree, it does not allow me to render all the nodes passed to it. For my screen resolution it allows ~400000 nodes. For a bigger resolution, it increases the number of nodes rendered.

**Comment by jameskerr** [comment]
I'm not sure I understand your issue. I do believe I need to document how to make react arborist fill up the height of a container. Maybe that is what you are running into.

I will close this issue, but please comment on it if you wish to provide more information.
