### ISSUE TITLE
treeRef.current.scrollTo(id) fires a ts console.error 

### ISSUE THREAD

**Issue by n3xtd0** [brimdata/react-arborist#136]
executing treeRef.current.scrollTo(nodeId) fires a ts console.error saying:

"Uncaught TypeError: Failed to execute 'scrollTo' on 'Element': The provided value is not of type 'ScrollToOptions'."

on README.md says that scrollTo receives an "Id" and an optional "align" param. But on ts definitions that is not the case:
`scrollTo(options?: ScrollToOptions): void;
    scrollTo(x: number, y: number): void;`

![image](https://user-images.githubusercontent.com/57770480/230099487-184e17b7-876e-4a29-8cae-d4295a5544dd.png)

**Comment by jameskerr** [comment]
It looks like you don't have the "tree" instance in your ref, but rather an HTML element. Where is your ref attaching to the tree component? Make sure it's not attaching to a div or something.

**Comment by n3xtd0** [comment]
It seems you are right. I was attaching the ref to the wrapper. Thanks!

**Comment by jameskerr** [comment]
Great!
