### ISSUE TITLE
Disable delete and create

### ISSUE THREAD

**Issue by Louqcode** [brimdata/react-arborist#137]
Hi! 

Is there a way to disable delete and create in an uncontrolled tree, in the same way as e.g `disableEdit`? I would like to always disable create and disable delete for leaves

If not, is it possible to add as a new feature? Thanks!

**Comment by jameskerr** [comment]
I believe you can attach an onKeyDown listener to the node and call e.preventDefault when the delete key is pressed. Do the same for "a" and "shift+a". Those are the create keyboard shortcuts.

**Comment by jameskerr** [comment]
I will address this in #57 . You'll then be able to customize what the delete key does. Closing as part of that ticket.
