### ISSUE TITLE
Missing class properties transform

### ISSUE THREAD

**Issue by fadimakram90** [brimdata/react-arborist#139]
I am getting the following error:
`\node_modules\react-arborist\dist\module.js: Missing class properties transform`
I am using create-react-app, so I have no straight option to update the webpack config file.

**Comment by jameskerr** [comment]
This seems like a babel issue or some problem your development setup. I'm not sure I can do anything from my end. I hope you get it figured out! If you find something that is a problem in this lib, please let me know.
