### ISSUE TITLE
Configurable Drop Cursor

### ISSUE THREAD

**Issue by jameskerr** [brimdata/react-arborist#14]
The styles are hard-coded at the moment

**Comment by barbalex** [comment]
Yep. Would also be nice to be able to define where a node can be dropped. And choose matching cursors (droppable <> not droppable here)

**Comment by jameskerr** [comment]
Excellent idea @barbalex . The drop cursor renderer can be given the "can drop" boolean to render something different in those cases.

**Comment by barbalex** [comment]
> The drop cursor renderer can be given the "can drop" boolean to render something different in those cases.

Is that an idea or can that be done currently? If so: how?

**Comment by barbalex** [comment]
I think tha last missing piece is to know what the dragged node is hovering over. 

Only thing I found was `isHoveringOverChild`. In my case I would need to know if it was hovering over siblings. Or a more general solution: get the hovered node's data.

**Comment by jameskerr** [comment]
Makes sense, I'll update this thread when I implement this ticket.

**Comment by barbalex** [comment]
This one: https://github.com/barbalex/capturing

An app to collect data outside of the office, alone or in teams. Universal, offline, deals well with conflicts. Well, that is the basic idea.

I have other apps like https://github.com/barbalex/vermehrung, https://github.com/barbalex/apf2 and https://github.com/barbalex/ae2 that also use navigation-trees.
