### ISSUE TITLE
When dragging one Node over another Node will be children

### ISSUE THREAD

**Issue by masoi1289** [brimdata/react-arborist#140]
![image](https://user-images.githubusercontent.com/38401005/232414797-777ab84a-79cf-43d4-8c04-489cfdd7c660.png)

I want When drags 'Alice' over 'Bob' for a few seconds Bob allows drop and 'Alice' will be Bob's child.

@jameskerr can you support me with this issues? Thanks

**Comment by masoi1289** [comment]
When I set children: [] It can't move to Root it always detect to be child random node

**Comment by jameskerr** [comment]
I've never tried this. I hope you can find a way to do it. I imagine that all the nodes would need to be considered "internal" with an empty children array. 

Maybe you could temporarily create an enclosing folder after a certain time hovering of a node.

**Comment by jameskerr** [comment]
Thank you for your feedback. I'm going to close this in favor of #144.
