### ISSUE TITLE
Outside click clears selection

### ISSUE THREAD

**Issue by bfsgr** [brimdata/react-arborist#142]
Hi, I noticed that a click outside a Row will clear the selection and I couldn't find a way to prevent that. I believe that `ListOuterElement` is clearing the selection, is there a way to stop it from doing so?

https://github.com/brimdata/react-arborist/blob/4c3368f297e5f995a98ce31a3c5faf82a02c05ee/packages/react-arborist/src/components/list-outer-element.tsx#L18

**Comment by jameskerr** [comment]
That is the behavior I witnessed on other types of tree interfaces. If you click in the blank area below the rows, it will deselect the items.

This is how it works in the Mac Finder for instance.
![CleanShot 2023-05-10 at 15 49 56](https://github.com/brimdata/react-arborist/assets/3460638/98ab2bf4-c88a-4efb-ad80-e2c70c4a748a)

I'm going to close this for now, but feel free to comment on your particular use case here in the issue.

**Comment by ScarletJack** [comment]
Could a prop be added such as `closeOnClickOutside={false}`? 

I would also like the feature of keeping the selection when building a navigation tree or a merge tree.
