### ISSUE TITLE
Unsupported URL Type "workspace:": workspace:^

### ISSUE THREAD

**Issue by Ochk0** [brimdata/react-arborist#143]
When I try to run     "start:showcase": "yarn workspace showcase start"
Unsupported URL Type "workspace:": workspace:^ this error appear and when I statically typed the latest version it says dependency not found in the code.

**Comment by jameskerr** [comment]
I'm not sure what is the problem. 

What kind of node version are you on. What type of yarn version?

This repo makes use of yarn workspaces. It looks like your running into a problem in that area.

**Comment by GilbertSun** [comment]
> When I try to run "start:showcase": "yarn workspace showcase start" Unsupported URL Type "workspace:": workspace:^ this error appear and when I statically typed the latest version it says dependency not found in the code.

you can  goto `react-arborist` and run `yarn build`

**Comment by jameskerr** [comment]
@Ochk0 I hope you were able to get this working. The project uses yarn workspaces.
