### ISSUE TITLE
External selection mgmt

### ISSUE THREAD

**Issue by markwatabe** [brimdata/react-arborist#15]
This works pretty well. I've been comparing this package to a bunch of other react trees, and I am most hopeful this will work for my use case.

One thing I find strange is I can only access selection state from inside the Node renderer.  Why not expose onSelect the same as you do with onEdit and onToggle, to make it easier for syncing with the selection state of the tree?

Related, you added an onClick prop (that isn't listed on the documentation page) and I'm wondering if that was meant to make it possible to configure external selection state synching? It fires the synthetic click event and not some computed state object so I'd be we wary using that to try and set up outside mgmt.

Am I missing something?

**Comment by markwatabe** [comment]
ah, nm. I realized you can access those methods on the ref handler. Thanks for making this package!

**Comment by jameskerr** [comment]
@markwatabe I pondered this same question. In the end, I decided to make the methods available on the ref as you discovered. Here is a piece of code I wrote for the brimdata/brim app that selects an item in the tree whenever the external selection changes.

https://github.com/brimdata/brim/blob/79640b32f3b74d5dc49dd7b3e5546efaebc17791/src/app/features/sidebar/queries-section/index.tsx#L135-L142

Here is a video showing that piece of code in action.  The tree component selects the correct item when the tab switches.


https://user-images.githubusercontent.com/3460638/160152953-fc71977a-d275-4ed5-b48d-45439a1b8812.mov

**Comment by jameskerr** [comment]
I need to document the Tree's onClick and onContextMenu props. Those are attached to the tree container so that you can take action when the user clicks or rightclicks on an area of the tree that has no items. Maybe you clear the selection, or provide a different context menu.


About a year ago I did the same search for a tree library and couldn't find one flexible enough, hence react-arborist. If you don't mind sharing, I'd love to hear what your use case is.

**Comment by jameskerr** [comment]
@markwatabe Was there anything in the dev console when your other drag and drop functionality died? I'll make an issue.

**Comment by jameskerr** [comment]
Also @markwatabe what kind of library (or not) are you using for the other drag and drop functionality in your app?

**Comment by markwatabe** [comment]
It seemed like the presence of this library seemed to kill the default behavior of other components that had onDrag, onDrop, etc events. That is to say I toggled on and off importing this library and that seemed to fix the problem. That being said, I might have had other libraries loaded that could have created a complex situation?

I can try and reproduce in the next couple of days and post the isolated code.
