### ISSUE TITLE
controlled tree: how to edit newly created node

### ISSUE THREAD

**Issue by direbunny** [brimdata/react-arborist#151]
When I use Tree with `initialData` everything works fine. I switched to `data` and I see that onCreate is called and I am able to add a new node to the data.

Unfortunately though, that new node is not in edit mode. I don't see a way to access the NodeApi from within the onCreate handler (since the node is not yet created).

Is there a way to have new nodes enter edit mode when using the Tree as a controlled component? Thanks!

**Comment by direbunny** [comment]
Not sure what was going on here, but I'm not seeing this issue anymore. I'll repost if I see it again.

**Comment by holy-dev** [comment]
How are you creating new nodes?

**Comment by jameskerr** [comment]
The 'a' character on the keyboard is the default keybinding for creating a new node. 'shift+a' for creating a new folder.
