### ISSUE TITLE
node.edit() not working

### ISSUE THREAD

**Issue by andleebsyed** [brimdata/react-arborist#152]
Hey there
My use case is to rename a certain node
When i trigger it by calling `node.edit()` , i get this error `TypeError: Cannot read properties of undefined (reading 'id')`
Not able to figure out what the issue is , as the other things like moving items, creation of folders are working fine.

**Comment by remorses** [comment]
This happens if you pass down the props `node.submit` or `node.reset` like this `<Input submit={node.submit} />`

You should pass the whole node instead, something like `<input node={node} />`, this way `this` inside the node methods will be defined correctly
