### ISSUE TITLE
Unable to create or delete node

### ISSUE THREAD

**Issue by holy-dev** [brimdata/react-arborist#161]
I cannot find any documentation on how can I create a new or delete an existing one

**Comment by jameskerr** [comment]
Right now they are bound to keyboard shortcuts. But they also can be done through the tree and node apis.

'a' create leaf
'shift+a' create folder
'backspace' delete

**Comment by holy-dev** [comment]
It's not working, I'm using it with next js with new app router.

**Comment by holy-dev** [comment]
I created a blank project & tried it, and it worked. Must be some issue with my setup. Could you give me an example of onCreate?

**Comment by holy-dev** [comment]
Found the issue. It's breaking when using it with tailwindcss.

**Comment by holy-dev** [comment]
@jameskerr I got it to work. But when I'm using onCreate it's not working. I don't understand how It can work.

Please help me. It lacks documentation. Do you need any help with the documentation? I would love to help you.

**Comment by jameskerr** [comment]
Are you using `data` or `initialData` when trying to create nodes?

If you are using `initialData`, you can use the `tree.createLeaf()` or `tree.createInternal()` apis to update the tree.

If you are using the data prop, they you'll need to manage the tree data yourself.

When you use initialData, this is the callback that is passed to the tree's onCreate prop automatically.

https://github.com/brimdata/react-arborist/blob/main/packages/react-arborist/src/hooks/use-simple-tree.ts#L44-L50

**Comment by holy-dev** [comment]
I'll look into it and update you. Do you need any help with the docs? I'll be honest the package is really awesome but there's not enough docs.

**Comment by holy-dev** [comment]
@jameskerr it does not take data object

```javascript
const onCreate: CreateHandler<T> = ({ parentId, index, type }) => {
    const data = { id: `simple-tree-id-${nextId++}`, name: "" } as any;
    if (type === "internal") data.children = [];
    tree.create({ parentId, index, data });
    setData(tree.data);
    return data;
 };
```

It's from the link you gave

tree.create accepts only
```javascript
method) TreeApi<Data>.create(opts?: {
    type?: "internal" | "leaf" | undefined;
    parentId?: string | null | undefined;
    index?: number | null | undefined;
} | undefined): Promise<void>
```

There's no data

**Comment by mawnir** [comment]
> @jameskerr it does not take data object
> 
> ```js
> const onCreate: CreateHandler<T> = ({ parentId, index, type }) => {
>     const data = { id: `simple-tree-id-${nextId++}`, name: "" } as any;
>     if (type === "internal") data.children = [];
>     tree.create({ parentId, index, data });
>     setData(tree.data);
>     return data;
>  };
> ```
> 
> It's from the link you gave
> 
> tree.create accepts only
> 
> ```js
> method) TreeApi<Data>.create(opts?: {
>     type?: "internal" | "leaf" | undefined;
>     parentId?: string | null | undefined;
>     index?: number | null | undefined;
> } | undefined): Promise<void>
> ```
> 
> There's no data

have you found a solution?

**Comment by CHE1RON** [comment]
These are hooks being passed to `Tree`, not actions to be carried out. What @jameskerr is trying to tell you is this: When using `data`, you have to make changes to the `data` you're passing to `Tree`, then it will be updated accordingly!

**Comment by jameskerr** [comment]
Thank you @CHE1RON for your attention to this and the other issues :)

**Comment by CHE1RON** [comment]
Thank you for this fine library 😉
