### ISSUE TITLE
How to open and close a node

### ISSUE THREAD

**Issue by elmcapp** [brimdata/react-arborist#164]
I have 2 issues:

1. All nodes with children are open by default. Is there a way to have them closed?
2. When I click on a parent node (node with children) it does not close. Is there a way to make them open and close when you click them?

````
type NodeType = { node: NodeApi; style: any; dragHandle: any };

function Node({ node, style, dragHandle }: NodeType) {
  const customStyles = {
    display: "flex",
    alignItems: "center",
    ...style, // Merge the received style prop with custom styles
  };
  
  return (
    <div style={customStyles} ref={dragHandle}>
      {node.isLeaf ? (
        <Play size={20} />
      ) : node.isOpen ? (
        <ChevronDown size={20} />
      ) : (
        <ChevronRight size={20} />
      )}
      {node.data.name}
    </div>
  );
}

function ScenePanel() {
  return (
    <div>
      <PanelWindow
        isVisible={true}
        className="scene"
        panelTitle="Scenes"
        onDismiss={() => {}}
        positionY={0}
        positionX={0}
      >
        <Tree initialData={demoData}>{Node}</Tree>
      </PanelWindow>
    </div>
  );
}
````

**Comment by holy-dev** [comment]
1. You can use openByDefault={faslse} in the <Tree /> component
2. You can do something like this
` <div
      ref={dragHandle}
      style={style}
      className={clsx(styles.node, node.state)}
      onClick={() => node.isInternal && node.toggle()}
    >
      <div className={styles.indentLines}>
        {new Array(indentSize / INDENT_STEP).fill(0).map((_, index) => {
          return <div key={index}></div>;
        })}
      </div>
      <FolderArrow node={node} />
      <Icon className="mr-2 shrink-0" />{' '}
      <span className="flex-1 overflow-hidden text-ellipsis">
        {node.isEditing ? <InputField node={node} /> : node.data.name}
      </span>
    </div>`

**Comment by jameskerr** [comment]
Thank you @holy-dev

**Comment by holy-dev** [comment]
> Thank you @holy-dev 

Brother, please help me too. Please see my open cards.
