### ISSUE TITLE
Saving tree state. Refresh page in keep tree order & tree open state

### ISSUE THREAD

**Issue by elmcapp** [brimdata/react-arborist#166]
Is it posible to keep the state of the tree such as when we reorder tree items and if we open a child node. 

I have a Reactjs project and I would like to store in async storage or in browser storage the last order of the list created by the user if they was to refresh there page. I would also like to recall the open or close state of tree items. 

example 

```
- Apples
- Banana
   |- new
   |- old
- Orange
```

Now lets say that I change the list like this (Notice I close Banana so that its children don't show and I reordered the fruit)
```
- Banana
- Orange
- Apples
```

If I refresh the page everything will return to the first state. Is there a way I can store everything in the browser so that it returns back to the way I organize the list. 

Can someone provide a very basic example

**Comment by elmcapp** [comment]
So I figured out how to save and store the open and close state and recall them. We just use the ```initialOpenState``` prop.

Now I need to figure out how to get the ```initialData``` value after its change. For example If I was to move the node Apples in the place of Orange Is there a prop that I could get the updated full tree data in the new order it is in. If not how do I do this and could you provide an option to do this as a onChange prop


````
<Tree
          initialData={demoData}
          openByDefault={false}
          initialOpenState={{ 3: true, 4: true }}
          
        >
          {Node}
        </Tree>
````

**Comment by jameskerr** [comment]
You could get the the tree instance in a ref as described here: https://github.com/brimdata/react-arborist#use-the-tree-api-instance

Then you could call `tree.root`. That will give you the root node of the tree. It will look a little different than your data. 

You could also use the internal helper hook, useSimpleTree.

https://github.com/brimdata/react-arborist/blob/fbf0290c7313966ca12b63f887761275ad0f4697/packages/react-arborist/src/hooks/use-simple-tree.ts#L19

Use it like this:

```jsx
const [data, controllers] = useSimpleTree(myInitialData)

return <Tree data={data} {...controllers} />
```

**Comment by elmcapp** [comment]
Just asking for further. Could you create a discussion this way when we need help we can talk about that in GitHub Discussions and we can use issues from bugs or problems? Just asking

**Comment by jameskerr** [comment]
Sure, I've never used GitHub discussions. I'll look into enabling it.

**Comment by mawnir** [comment]
> You could get the the tree instance in a ref as described here: https://github.com/brimdata/react-arborist#use-the-tree-api-instance

can you show an example of this?
