### ISSUE TITLE
DnD with auto sorting - equivalent of a VSCode sidebar

### ISSUE THREAD

**Issue by MarekPrzydanek** [brimdata/react-arborist#178]
Hi!

I'd like to copy drag & drop UI from VSCode (without choosing leaf order) like below:
![VSCExplorer](https://github.com/brimdata/react-arborist/assets/51137794/e06c17c2-d3ed-4580-923f-e5a5b0480bb9)
When I drag File4.txt from FolderB to files in FolderA the files 1, 2, 3 and FolderA all have hovered state. I can't find a way to do that in Arborist. 

The main problem is that I can't get any information about dragging over or between the leafs.
![image](https://github.com/brimdata/react-arborist/assets/51137794/ae7d7362-e247-441e-a528-0962e9a29761)
When the cursor is active between the files I can't get its state from the node component.

I managed to highlight all nested children when hovering over the parent internal node (FolderA) using the following code:
```
let parent = props.node.parent;
while (parent) {
	if (parent.willReceiveDrop) {
		return true;
        }
	parent = parent.parent;
}
return props.node.willReceiveDrop;
```

In the docs I read that `<RowRenderer>` is responsible for attaching the drop ref but I couldn't figure anything out.

Since the readme states that we can build the equivalent of a VSCode sidebar could you provide a sample or correct the description if it's impossible?

**Comment by jameskerr** [comment]
Hey there! You're right. I was not able to re-create VSCode with the current version, despite my marketing claims :) 

I've get a branch started to make the changes necessary to do what you want here as well as add a VSCode demo to the demo website.

Take a look: https://github.com/brimdata/react-arborist/pull/179

**Comment by MarekPrzydanek** [comment]
I finally got the time to check it out in version 3.4.0 and I can confirm it works flawlessly :)

Thanks!

**Comment by jameskerr** [comment]
Fantastic!
