### ISSUE TITLE
Bug: You have a basic bug from the first version of your package, and that is the failure to convert the ES6 code above into a language that can be converted for the browser

### ISSUE THREAD

**Issue by jzarei1996** [brimdata/react-arborist#196]
When I install your package on my project, the webpack version is as follows:

`
"webpack": "^4.41.5",
"webpack-cli": "^3.3.12"
`
I encounter such an error:

ERROR in ./node_modules/react-arborist/dist/index.js 132:9
Module parse failed: Unexpected token (132:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
}
     // @ts-ignore ??
>   next?.focus();
}

According to my searches, this is a bug in webpack version 5 and below. My problem is that I can't update the version of Webpack, Babel, etc.

Here is a link to report such an error in webpack that you can use:
[https://github.com/webpack/webpack/issues/10227](url)

It seems the best way is to convert the code and ES6 features to higher 
It should be done by your package itself. Please do this for your first package version and above.
Thanks

**Comment by jameskerr** [comment]
Thanks for the write up and sorry you're having issues. I don't plan to fix this in my package and will close this issue. Good luck. Hopefully you can upgrade soon!
