### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by jossmac** [brimdata/react-arborist#20]
Consider accomodating users of assistive tech, with the appropriate [roles and aria attribution](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tree_role).

**Comment by jameskerr** [comment]
Thanks @jossmac, this is being tracked in #9 . It's first on my priority list.

**Comment by jossmac** [comment]
Sorry mate, missed that. Glad to hear it 👍
