### ISSUE TITLE
Help with keeping expanded states

### ISSUE THREAD

**Issue by chrispalm** [brimdata/react-arborist#203]
Hi,

As title said I've been trying to figure out how to keep track of expanded states for nodes in my tree. Used another tree-component before this one and there you had a property with a list of ids defining the visible nodes and the tree would then expand these. I tested the initialOpenState but that didn't seem to do what I want, nothing was opened but maybe I'm not using it correctly, couldn't find any example code as how to use it. I need to be able to both insert a list of ids at start of application and then at any point be able to update this list with other values. Any pointers as how to get this working?

Br and Thanks
Christian

**Comment by au-re** [comment]
Hi Christian! I was wondering the same thing. Here is how I got it working:

You can configure the `initialOpenState` to change what nodes should be open/closed initially. You need to provide a map where the keys are the node ids and the values are true for open and false for closed.

```jsx
return (<Tree
   ...
   initialOpenState={{ 
      myNodeId1: true | false,
   }}
>
{Node}
</Tree>)
```

To control the open / closed state of a node from outside the tree, you can use the Tree API:

```jsx
const treeRef = useRef(null);

useEffect(() => {
  const tree = treeRef.current;
  tree.open(myNodeId1);
}, []);

return (<Tree
   ref={treeRef}
>
{Node}
</Tree>)
```

Hope this helps!

**Comment by chrispalm** [comment]
Great! That's awesome, thank you very much for taking the time to help me.

BR
Christian

**Comment by zhangwei900808** [comment]
@au-re why I set open node with cid but not work?
```
useEffect(()=>{
        if (query.get('cid') && treeRef.current){
            treeRef.current.open(query.get('cid'))
        }
    }, [])


<Tree data={treeData}
              ref={treeRef}
              width={'100%'}
              height={treeHeight}
              selection={query.get('cid')}
              rowHeight={36}
              indent={12}
              openByDefault={false}
              disableDrop={true}
              disableMultiSelection={true}>
            {renderTreeNode}
        </Tree>
```

**Comment by zhangwei900808** [comment]
I had resoved it
```
if (query.get('cid') && treeRef.current) {
            const fs = urlCategories.filter(f => f.id === query.get('cid'))
            if (fs.length > 0) {
                if (fs[0].pid){
                    treeRef.current.open(fs[0].pid)
                }
            }
        }
```

**Comment by doulighan** [comment]
How would you persist the current open state on each state change? Check the ref each render or something?

**Comment by jameskerr** [comment]
This will all get easier in version 4.
