### ISSUE TITLE
Line breaks in long strings

### ISSUE THREAD

**Issue by rogerok** [brimdata/react-arborist#204]
Hi, how i can handle line breaks in long string?
Now, if add css rule 'white-space: pre-wrap', then layout breaks.
![image](https://github.com/brimdata/react-arborist/assets/55946493/3f34c4eb-ff57-47dd-95ab-5d7dbf6d3911)

**Comment by jameskerr** [comment]
I usually do

```
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```

**Comment by smorodin-it** [comment]
Same issue here. PM want to see whole label. Any suggestion to how I can break for two lines, and fix a layout issue as from screenshot above?
