### ISSUE TITLE
Remove unnecessary "height" prop, Support custom scroll bars

### ISSUE THREAD

**Issue by michaelspiss** [brimdata/react-arborist#21]
First of all, thanks for creating this package!

Currently, the tree only works with static widths and heights (using observers excluded).
However, since the tree height is already calculated in `OuterElement` in `tree.tsx`, I don't see why a static height would be required.

I did some quick tests - passing the calculated tree height to the enclosing `position: relative` div and changing the `overflow` values was already enough to get rid of the "height" prop requirement.

Bonus: Custom scroll bar libraries also started working correctly.

**Comment by michaelspiss** [comment]
I just noticed that this would break the "scroll to item" functionality.
Maybe a better approach would be to provide a callback with the calculated height on update.

**Comment by jameskerr** [comment]
Thanks for bringing this up! I address your question in the other issue, but I don't see why I couldn't add a method to the tree api that gets the total tree height, the same calculation we do in the OuterElement.
