### ISSUE TITLE
Item count increases randomly

### ISSUE THREAD

**Issue by CHE1RON** [brimdata/react-arborist#214]
Hey there,
first off, I really like this library! 🙏 

However, while experimenting with it, I noticed that my tree adds multiple clones (see video):

https://github.com/brimdata/react-arborist/assets/122524301/48502fd3-0315-47a0-bc49-fb771b195f4f

The passed `data` array only contains three nodes, but as you can see, they are duplicated 😕

I'm loading data using `react-query` (which calls an endpoint via `axios`), feeding it to the `data` prop of `Tree`:

```typescript
export const TreeView = () => {
  // ...

  // Fetch data
  const { data } = useSuspenseQuery(getNodesQuery(id));

  // Define handlers
  const createFolder = useCreateFolder(id);

  return (
    <Suspense fallback={'Loading ..'}>
      <Button
        label="Create folder"
        onClick={() => {
          // TODO: Replace with modal/input, etc ..
          const name = folderName();
          void createFolder.mutateAsync(name);
        }}
      />
      <FillFlexParent>
        {({ width, height }) => (
          <ArboristTree
            data={data}
            height={height}
            idAccessor="someId"
            indent={16}
            width={width}
            ref={treeRef}
          >
            {NodeRenderer}
          </ArboristTree>
        )}
      </FillFlexParent>
    </Suspense>
  )
}
```

Any pointer in the right direction is much appreciated! 👍 

Cheers,
CHE1RON

**Comment by jameskerr** [comment]
Looks like you found the issue!
