### ISSUE TITLE
Hidden flag for nodes

### ISSUE THREAD

**Issue by harrycollin** [brimdata/react-arborist#216]
It would be great if we can exclude nodes from rendering based on a flag/property in the data (Example: `hidden: true`). My data structure contains children that shouldn't be rendered. Reconstructing the data would be difficult and would break references in other parts of my app. I feel like this should be something that's quite simple. Perhaps I've even missed something in the documentation which allows for this behaviour.

**Comment by jameskerr** [comment]
Interesting use case. I suppose this could be added in a future version.
