### ISSUE TITLE
Access to tree height after rendering

### ISSUE THREAD

**Issue by michaelspiss** [brimdata/react-arborist#22]
Is there a way to get the tree's height? The only way I've found is by multiplying the `rowHeight` with `tree.visibleNodes()` - but the latter is only available inside the node renderer.
I'd like to use custom scroll bars with this package.

**Comment by jameskerr** [comment]
Oh I see what you mean. You need the height of the whole list. Not the scroll container. I suppose you could do that with what you did above. The tree api is available from the parent component if you pass a ref to the Tree component.

Maybe something like this in your parent component: 
```jsx
const tree = useRef()
const rowHeight = 20

useLayoutEffect(() => {
  // tree.current is the same "tree" prop passed to the node renderer.

  const height = tree.current.visibleNodes() * rowHeight
}, [tree.current && tree.current.visibleNodes()])

return <Tree ref={tree} rowHeight={rowHeight} />
```

**Comment by michaelspiss** [comment]
Ah, being able to get to the tree api from the parent element changes things!

This is how I made it work (with types), should anyone else stumble upon the same problem:
```typescript
const [treeHeight, setTreeHeight] = useState(0);
const treeRef = useRef<TreeApi<any>>(null);

useLayoutEffect(() => {
    setTreeHeight(rowHeight * (treeRef.current?.visibleNodes?.length ?? 0));
}, [treeRef.current?.visibleNodes]);

return  <Tree<any> ref={treeRef} height={treeHeight} />
```

(The `height` prop on `Tree` is required to disable "native" scrollbar flashes. `any` being the tree item's props type.)

Thanks again @jameskerr, for your help and this awesome package!
