### ISSUE TITLE
Control selection state (selectedIds) outside of NodeRenderer

### ISSUE THREAD

**Issue by huyha1408** [brimdata/react-arborist#24]
Is there any way to do this?

**Comment by jameskerr** [comment]
Yes, it's not documented very well, but you can attach a ref to the Tree component and access the TreeApi. All the methods listed here: https://github.com/brimdata/react-arborist#tree-prop

```jsx
const tree = useRef()

useEffect(() => {
  tree.current.selectById("123")
}, [])

<Tree ref={tree} />
```
