### ISSUE TITLE
README example renders nothing visible

### ISSUE THREAD

**Issue by codyburleson** [brimdata/react-arborist#25]
I've created a new react apop using create-react-app and updated App.js with the example from the project's GitHub README so that I can start experimenting and learning, but the example given renders nothing for me. In the React Developer Tools, I can see the nodes are there, but I have no idea yet how to make them visible.

Shown below is what I see in the Components tab of the tools...

![image](https://user-images.githubusercontent.com/7317733/166844613-8d51fdfe-a1d6-4da7-9ad8-a419a7156049.png)

Following is my `App.js`...

```js
import './App.css';
import { Tree } from "react-arborist";

const data = {
    id: "The Root",
    children: [{ id: "Node A" }, { id: "Node B" }]
}

function Node({ ref, styles, data }) {
    return (
        <div ref={ref} style={styles.row}>
            <div style={styles.indent}>
                {data.name}
            </div>
        </div>
    )
}

function App() {
    return (
        <div className="App">
            <div className="workspace-leaf-content" data-type="collection-manager">
                <div className="view-content">
                    
                    <h4>React Arborist Tree Component Test</h4>
                    
                    <Tree data={data}>{Node}</Tree>

                </div>
            </div>
        </div>
    );
}

export default App;
```

But, as you can see, nothing renders...

![image](https://user-images.githubusercontent.com/7317733/166844951-e12751b3-7c1d-4bce-9cb7-ecf5f561166a.png)

I am guessing the README just assumes one knows more than I do about React or something. I could use a hint! Or do you sell consulting hours?

**Comment by codyburleson** [comment]
Actually, I just got something rendered by changing my data to actually include a `node.name`...

```js
const data = {
    id: "The Root",
    children: [
        { id: "Node A", name: "Node A" },
        { 
            id: "Node B", 
            name: "Node B",
            children: [
                { id: "Node B.1", name: "Node B.1" },
                { id: "Node B.2", name: "Node B.2" }
            ]
        }
    ]
}
```

I didn't realize you were assuming we would assume that any additional properties could go in each node when you defined what the node structure should be. That's a little vague, but I get it now.

The questions still stands whether you sell consulting hours, however.

**Comment by jameskerr** [comment]
Hi @codyburleson , thanks for your question. I'm glad you figured it out. I agree, the readme is a little vague on that part. Feel free to send a PR with some improved wording if you feel like it!

I don't have much time for consulting hours, but I am happy to answer any questions you'd have here on github. Good luck and I hope it works out for you.
