### ISSUE TITLE
Scroll offset issue when click edit button in the provided demo 

### ISSUE THREAD

**Issue by ariannargesi** [brimdata/react-arborist#26]
Thanks for this great library.
I'm looking at the [this](https://react-arborist.netlify.app/) demo and when I click on the edit button (hand that hold a pen), everything move up and input will stick to top of the container.

**Comment by jameskerr** [comment]
Could you by chance show me a video or gif of what you're seeing? I just clicked the demo and it didn't do that for me. But I know what you mean. There is some code that scrolls the item into view if it's out of view when the edit handler is called.

**Comment by ariannargesi** [comment]
Sure! 
I looked it more carefully. This only happens when scrollbar it's not at the bottom of the main container.
OS: Ubuntu 22.04
Browser: Chromium

https://user-images.githubusercontent.com/46089900/167477271-99191596-38ca-43d4-a29a-cddb6a10d5d1.mp4

**Comment by jameskerr** [comment]
Thank you!
