### ISSUE TITLE
Prevent dragging of individual nodes

### ISSUE THREAD

**Issue by report-zone** [brimdata/react-arborist#283]
Is there a way to prevent dragging of specific individual nodes ?

**Comment by report-zone** [comment]
Never mind, figured it out.

**Comment by jokerham** [comment]
For anyone looking for sample...

`const MenuNode = ({node, dragHandle}: NodeRendererProps<IMenu>) => {
  const isRootNode = node.parent?.isRoot;
  const drag = !node.data.isRootNode ? { ref: dragHandle} : {};
  return (
    <div node={node} {...drag}>
      {node.data.name}
    </div>
  )
}`
