### ISSUE TITLE
How to move a node to the child of a leaf node?

### ISSUE THREAD

**Issue by gcjjyy** [brimdata/react-arborist#29]
Hello,

I'm looking for a way to move a node to the child of the other leaf node.

Currently, I can move nodes into exisiting folder nodes (it means they have children already)

Please help me!

**Comment by jameskerr** [comment]
Great question! I think this is doable with the library as is. The drag and drop logic checks to see if a node is a "folder" before allowing a drop into it. But the logic for if a node is a "folder" is `!!data.children`. So you if you want to treat all nodes as "folders", then you could just set their children property to an empty array. That should do it!

**Comment by gcjjyy** [comment]
@jameskerr Thank you so much!! It's really awesome and customizable component!!!

**Comment by songispm** [comment]
Can you add a option like "dropWithoutChildren: true" @jameskerr 

Although children don't exist, they can still be dropped.
