### ISSUE TITLE
Drag Handle

### ISSUE THREAD

**Issue by impactvelocity** [brimdata/react-arborist#38]
Love what you have made!!

Learning so much by reading the source. Fantastic job.

I would love a drag handle ref option. 

packages/react-arborist/src/components/row.tsx   maybe expose optionally the dragRef ?

Thanks!

**Comment by jameskerr** [comment]
Thank you! 

Help me understand. Do you mean you want to control where in the row you can begin a drag? Can you help me understand what you are building?

**Comment by impactvelocity** [comment]
Yes, where the control could be begin drag. Like a drag handle

React Dnd example of drag handle: https://react-dnd.github.io/react-dnd/examples/customize/handles-and-previews

Gif of what I am building:

https://share.getcloudapp.com/JruoERRK

In my example, I have a few action buttons, and drag can be a bit sensitive. So having lets say the icon (i have a cusor-move on ) would be the drag handle, so dragging becomes more intentional action from the user.

**Comment by impactvelocity** [comment]
@jameskerr Do you have an email? I can pay for your time for this feature and the drop cursor component. Also, if you have spare time for some maybe so other react stuff. :) 

If not, no worries!
