### ISSUE TITLE
Instead of position absolute, can we use nested tree?

### ISSUE THREAD

**Issue by jeevasusej** [brimdata/react-arborist#43]
Hi,

I have seen, we are using tree with absolute position to align tree items.
But can we use nested ul and li element to align trees?

**Comment by jameskerr** [comment]
In order to make the Tree render quickly with thousands of items, it only renders the rows that are in view. Therefore The items must be siblings in the DOM even though they are nested in the data. 

If they were nested, I would think all the items would need to be in the dom, which would lead to very bad performance with lots of items.

Also, may I ask why you would want them nested?

**Comment by jeevasusej** [comment]
Though we don't nested, If we use position relative or static, the way of stacked items will be in correct position.

Two issues I have faced in this plugin because of position absolute.
One is I need to fix the element height as u mentioned in the document. If I increase the height, the position top is miscalculated and the there is a gap between the items.

Second, in order to fix the issue, if I change to position relative, then there is rendering issue when scrolled to the end of the elements ..

**Comment by jeevasusej** [comment]
I have moved to fancytree which gives performance n also expected behaviour. I don't understand what kind of performance issues that you are facing when you are going with position relative or nested element. 

Thanks for your response. I appreciate your work.
But please concentrate on bug free plugin. 

[https://github.com/mar10/fancytree](https://github.com/mar10/fancytree)

**Comment by mooijtech** [comment]
Using https://github.com/ZeeCoder/use-resize-observer works as intended.

**Comment by jameskerr** [comment]
Yeah I always need to use that to fill the height and width as well.

**Comment by jeevasusej** [comment]
@mooijtech Are you telling overall tree height?? 
I am telling issue about tree node height. If we change the height, there is a gap between each node.

**Comment by jameskerr** [comment]
This library depends on  each node being the same height.

**Comment by jeevasusej** [comment]
I guess there is a option to set height for each node by the plugin itself. I will try to reproduce n give the sample
