### ISSUE TITLE
Error with multiple trees

### ISSUE THREAD

**Issue by lightsinthesky** [brimdata/react-arborist#46]
If you have 2 Tree components rendering at the same time a React `Maximum update depth exceeded` error is thrown. The line below is causing the error.

```js
useLayoutEffect(() => {
    // @ts-ignore
    dispatch(actions.setVisibleIds(api.visibleIds, api.idToIndex));  // <- causes the error.
  }, [dispatch, api.visibleIds, api.idToIndex, props.root]);
```

Here is a codesandbox with a basic repro.

https://codesandbox.io/s/react-arborist-forked-xb7ezj

Thanks!

**Comment by jameskerr** [comment]
Oh, interesting. Thanks for repro. This will get looked into.

**Comment by mooijtech** [comment]
This is solved by https://github.com/brimdata/react-arborist/pull/49 as the tree nodes is now an array.

**Comment by jameskerr** [comment]
Great to hear that!
