### ISSUE TITLE
Demo or code example of tree structure with connection lines

### ISSUE THREAD

**Issue by GabrielMil** [brimdata/react-arborist#59]
Hey the component is really cool but I would like to ask for an example with connection line (horizontal and vertical).
Is it possible to provide code example or add it to the api?
I tried doing it with css and custom render of the node but got confused.
Tnx!

**Comment by jameskerr** [comment]
Great idea! It is certainly possible.

**Comment by percy507** [comment]
Hi, 

I made a PR(#94) to add vscode-style structure lines for the cities demo. 

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/18365078/212613813-cab1f422-7abe-43d2-8f81-e248309bbde7.png">
