### ISSUE TITLE
disabledDrop and target/source drop monitoring

### ISSUE THREAD

**Issue by lightsinthesky** [brimdata/react-arborist#62]
Is there any facility in react-arborist to control dropping via source and target? More specifically can I limit dropping based on a combination of source key and target key? React DnD provides this via `canDrop` but `disabledDrop` is really just a static list. Thanks.

**Comment by jameskerr** [comment]
Would it suffice to have a `canDrop` prop on the <Tree /> that takes a function? The function would have the source and target as arguments and return a boolean. When false it restricts a drop.

I would image it would have the `dragNodes: NodeApi[]` and `targetNode: NodeApi | null` as arguments.

I wonder if it would be confusing to have `canDrop` and `disabledDrop` props.

**Comment by lightsinthesky** [comment]
> Would it suffice to have a `canDrop` prop on the that takes a function? The function would have the source and target as arguments and return a boolean. When false it restricts a drop.

Yes this would do it.

**Comment by rmeschian** [comment]
The canDrop feature would be extremely useful.  Dear @jameskerr, is there an estimate as to when this feature will be added?  If work has not started on this, I can try to do it myself and create a pull request - just want to avoid duplication of work.

Thanks so much in advance

**Comment by jameskerr** [comment]
@rmeschian Yes please work on this. I have not started yet. 

I think it would be best to add the draggingNodes as the second parameter to the disableDrop prop when a function is passed.

The new function signature would be:
```
disableDrop={(node: NodeApi, dragNodes: NodeApi[]) => boolean}
```

Go ahead and submit a pull request. Thanks!

**Comment by rmeschian** [comment]
@jameskerr please see https://github.com/brimdata/react-arborist/pull/98
-thanks

**Comment by jameskerr** [comment]
This is out now in version 3.0.1. Check out the release notes and see the new function signature. 

https://github.com/brimdata/react-arborist/releases
