### ISSUE TITLE
Tree inadvertently jumps when scrolling 

### ISSUE THREAD

**Issue by wrobbinz** [brimdata/react-arborist#75]
Reproduce: https://react-arborist.netlify.app/cities

1. Toggle Alabama to closed, then reopen.
2. Scroll down so that Abanda is off the screen and Abbeville is the topmost visible node
3. Slowly scroll up

Notice that the tree jumps up to Alabama. ~~The toggling from closed to open appears to be a necessary step~~ 🤔

4. Click something outside of tree e.g. focus the text input in the demo like in vid
5. Scroll up and down

Notice scroll behaves now.

The node being focused seems very relevant.

Video demo:

https://user-images.githubusercontent.com/7999878/205772329-535e569c-1a6d-42ce-98c6-b6b306ac8e68.mov

**Comment by jameskerr** [comment]
Weird! Thanks for noticing that and making the issue.

**Comment by wrobbinz** [comment]
Sure thing! Here's another vid showing the buggy behavior (hopefully this is insightful). Thought it was interesting it snaps to the center of the view, which reminded me of the couple instances of "smart" scroll behavior in the codebase.

https://user-images.githubusercontent.com/7999878/205766829-1433b93f-5aff-4992-b5b3-ae894ad28dc7.mov

**Comment by wrobbinz** [comment]
Okay, more investigating: This only happens when a node is focused (or perhaps when the tree has focus inside it). I've updated the OP with more detailed steps and a better video that shows that the tree scrolls nicely if you've focused on something outside of it.

**Comment by jameskerr** [comment]
That is very helpful. It seems like scrollTo method is being called when it doesn't need to be. Like when a <Row> is selected and re-mounted as we scroll up (the lib only mounts what's in the viewport). Something around that code maybe. I'm thinking in the useEffect that focuses a node in the <RowContainer>.

**Comment by wrobbinz** [comment]
Yeah, it's that useEffect. I have a solution, but I'm not entirely sure I've broken other logic in the process. Could use your eyes on it.

**Comment by jameskerr** [comment]
This tested out nicely and will be included in todays release.
