### ISSUE TITLE
Is there a way to specify heigh 100% of the container?

### ISSUE THREAD

**Issue by scudette** [brimdata/react-arborist#80]
Looking at the code it seems that I need to specify a fixed height for the tree in pixels (but this may not be known in advance for flex layout). Further the height is set in a style property so it is very hard to override it.

Is there a way to force the tree container to have a height of 100% - the resulting tree looks very weird with either the tree arbitrarily getting cut off at 500px height or if I specify something like e.g. 1000px it has two scrollbars because it exceeds the height of its container.

**Comment by mooijtech** [comment]
See https://github.com/ZeeCoder/use-resize-observer

**Comment by scudette** [comment]
Thanks!
