### ISSUE TITLE
Overscan for rendered rows?

### ISSUE THREAD

**Issue by rafma0** [brimdata/react-arborist#83]
Hi, is there any way to configure a number for overscan (or plans for adding it), like in react-virtualized?

Here's what their docs says about it
https://github.com/bvaughn/react-virtualized/blob/master/docs/overscanUsage.md

I have a large number of items (3k+) and depending on how fast the tree is scrolled I can see it struggling to catch up and it feels weird. If we can make it keep more items on top and bottom than what its currently showing, depending on the case the scroll feels much more natural.

edit:  they suggest to start at 10 and lower if possible but sometimes I like to use it at 100, so a configurable option would be ideal

Thank you for this amazing lib 😄

**Comment by jameskerr** [comment]
Hey there. Yes that is possible. This lib uses react-window for virtualization so we can pass it options for overscan. 

I've found the less overscan number the better performance.

What do you think the new props should be called? Probably just copy what react-window calls them.

**Comment by rafma0** [comment]
Good to know that its a simple change.

About the performance, what I noticed in my tests is, if you don't exagerate you can find a good balance.

It seems like they changed the default value from 10 in react-virtualized to 1 in react-window. I'd probably keep it at at least 10 in most of my projects anyway.

I think `overscanCount` like the original name is descriptive enoug :)
