### ISSUE TITLE
Pressing the 'a' key don't work for focus search

### ISSUE THREAD

**Issue by rafma0** [brimdata/react-arborist#85]
We can jump to an item if we start typing the name of it, which is nice,  but the letter 'a' also creates a new item, and it conflicts with the search

I tought of sending a PR changing
```js
if (e.key === "a" && !e.metaKey) {
  if (!tree.props.onCreate) return;
  tree.createLeaf();
  return;
}
```

to something like
```js
if (e.key === "a" && !e.metaKey && tree.props.onCreate) {
  tree.createLeaf();
  return;
}
```

as a temporary fix for people who don't need onCreate, but I don't know if you prefer to fix it in a different way, any toughts? ty

**Comment by jameskerr** [comment]
Yeah totally. I would welcome this fix. There are plans to offer custom keyboard shortcut mapping. See #76
