### ISSUE TITLE
Add keyboard interaction and ARIA roles

### ISSUE THREAD

**Issue by angrycat9000** [brimdata/react-arborist#9]
I saw your post on reddit.  Nice tree control.

I wanted to give a suggestion that could help take it to the next level.  Right now it is very mouse oriented.  However, not everyone may prefer to use the mouse.  If you look up the the [tree role on MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tree_role#keyboard_interactions) it documents keyboard interactions for a tree.  That way users can operate it without taking their hands off the keyboard if they prefer (similar to Ctrl-C Ctrl-V for copy and paste).

**Comment by jameskerr** [comment]
Thank you for your kindly worded suggestion.I plan to work on this very soon. This also came up on hacker news.

**Comment by esmevane** [comment]
If you're looking for prior art which might be helpful, [React-Aria has some examples of hook-based aria implementations](https://react-spectrum.adobe.com/react-aria/useListBox.html). Even when just used as implementation guides, it's been useful for me.

**Comment by Pustelto** [comment]
Definitely +1 for this. I haven't found a tree component which would support all the use-cases you have. The a11y is the only missing thing for me. Then I can remove this from my should-do-in-the-future OSS list. 

Here is the really good writeup how the tree should behave and what roles it should have: https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView

**Comment by jameskerr** [comment]
Thanks @Pustelto! I'll reference that as I work on it.

**Comment by jameskerr** [comment]
Here's a todo list for this issue:

## Keyboard Events

- [ ] **Right Arrow**
- [ ] When focus is on a closed node, opens the node; focus does not move.
- [ ] When focus is on a open node, moves focus to the first child node.
- [ ] When focus is on an end node (a tree item with no children), does nothing.
- [ ] **Left Arrow**
- [ ] When focus is on an open node, closes the node.
- [ ] When focus is on a child node that is also either an end node or a closed node, moves focus to its parent node.
- [ ] When focus is on a closed `tree`, does nothing.
- [ ] **Down Arrow**
- [ ] Moves focus to the next node that is focusable without opening or closing a node.
- [ ] **Up Arrow**
- [ ] Moves focus to the previous node that is focusable without opening or closing a node.
- [ ] **Home**
- [ ] Moves focus to the first node in the tree without opening or closing a node.
- [ ] **End**
- [ ] Moves focus to the last node in the tree that is focusable without opening the node.
- [ ] **Enter**
- [ ] Performs the default action of the currently focused node. For parent nodes, it opens or closes the node. In single-select trees, if the node has no children, selects the current node if not already selected (which is the default action).
- [ ] **Type characters**
- [ ] Focus moves to the next node with a name that starts with the typed character.
- [ ] If multiple characters are typed in rapid succession, focus moves to the next node with a name that starts with the string of characters typed.
- [ ] **\***
- [ ] Expands all siblings that are at the same level as the current node.

**Multi Selection** 

- [ ] **Space**
- [ ] Toggles the selection state of the focused node.
- [ ] **Shift + Down Arrow**
- [ ] Moves focus to and toggles the selection state of the next node.
- [ ] **Shift + Up Arrow**
- [ ] Moves focus to and toggles the selection state of the previous node.
- [ ] **Shift + Space**
- [ ] Selects contiguous nodes from the most recently selected node to the current node.
- [ ] **Control + Shift + Home**
- [ ] Selects the node with focus and all nodes up to the first node. Optionally, moves focus to the first node
- [ ] **Control + Shift + End**
- [ ] Selects the node with focus and all nodes down to the last node. Optionally, moves focus to the last node.
- [ ] **Control + A**
- [ ] Selects all nodes in the tree. Optionally, if all nodes are selected, it can also unselect all nodes.

## ARIA Roles
- [ ] [role="tree"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tree_role)
- [ ] [role="treeitem"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/treeitem_role)
- [ ] [aria-multiselectable](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-multiselectable)
- [ ] [aria-orientation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-orientation)
- [ ] [aria-level](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-level)
- [ ] [aria-setsize](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-setsize)
- [ ] [aria-posinset](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-posinset)
- [ ] [aria-owns](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-owns)
- [ ] [aria-expanded](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded)
- [ ] [aria-selected](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected)
