### ISSUE TITLE
forwardRef type overwritten

### ISSUE THREAD

**Issue by vitormarques-shape** [brimdata/react-arborist#95]
Hello.

I'm having an issue with the React.forwardRef type. When I include react-arborist dependency on my project and start using it, I start getting typescript errors, like this one: 
![Screenshot 2023-01-16 at 14 35 06](https://user-images.githubusercontent.com/86233953/212702877-662d8650-ff82-4cfc-8675-b4b872168158.png)
 
From what I gathered, react-arbortist redefines the forwardRef type with a module declared on `node_modules/react-arborist/dist/types/utils.d.ts`:

```
declare module "react" {
    function forwardRef<T, P = {}>(render: (props: P, ref: React.Ref<T>) => React.ReactElement | null): (props: P & React.RefAttributes<T>) => React.ReactElement | null;
}
```

What's the purpose of this type being redefined?

**Comment by slashwhatever** [comment]
Same. We are using MUI component library and this overwrite of the forwardRef definition breaks all the things :D

**Comment by jameskerr** [comment]
Forward Ref didn't work with components that accept generic type arguments. But maybe it's not needed anymore. I'll try to take it out.

https://fettblog.eu/typescript-react-generic-forward-refs/

**Comment by jameskerr** [comment]
I still needed this assertion: https://github.com/brimdata/react-arborist/pull/103
