### ISSUE TITLE
Api to prevent editing of individual nodes

### ISSUE THREAD

**Issue by danielnilsson9** [brimdata/react-arborist#96]
Thanks for this library, its great!

I am missing an API to prevent renaming of certain nodes in the same way drag and drop can be disabled to certain nodes. Is that something that would be of interest?

**Comment by jameskerr** [comment]
Thank you for the kind words. Yes that is a known limitation. Even the demos are broken in this way. We need to add another prop called disableEdit.

**Comment by danielnilsson9** [comment]
Sounds good, I will give it a go and send you a PR.

**Comment by jameskerr** [comment]
Thank you!

**Comment by jameskerr** [comment]
Fixed by #97
